### PR TITLE
simon game

### PR DESCRIPTION
**Pull request by saipranithswargam**
added a simple logical mind game using html,css,jquery,js

### CODE REVIEW

**Comment by SiddharthaBhattacharjee** [comment]
Please deploy your branch so that we can review it and decide if it shall be merged.

**Comment by SiddharthaBhattacharjee** [comment]
Another PR has been merged since the last time you made the PR, so please move your game position on the home page and name in contributors.md to accommodate the added game. Use "$ git pull" to get the latest updates.

**Comment by saipranithswargam** [comment]
I have pulled the branch and merged with mine and made necessary changes .

**Comment by SiddharthaBhattacharjee** [comment]
Please deploy the changed branch and mention he link in the next comment.

**Comment by saipranithswargam** [comment]
https://saipranithswargam.github.io/TimePassGames/

**Comment by SiddharthaBhattacharjee** [comment]
Thanks for contributing, your game is very nice, however, the game has some minor issues like the game not being able to reset in touchscreen mode, other than that, we might change a few things in the game in the future. Your PR is getting merged, there will be an issue created for the touchscreen problem soon.

**Comment by saipranithswargam** [comment]
just now i  have seen one typo in [CONTRIBUTORS.md].
its "Contriuters" instead of  "Contributors"

**Pull request merged**
