### PR TITLE
Dice Game

### PR DESCRIPTION
**Pull request by PathakTushar**
Dice game for two players made with js,html,css

### CODE REVIEW

**Comment by SiddharthaBhattacharjee** [comment]
Thank You for contributing, We need to evaluate your Pull Request before merging, so **please host your forked repo to GitHub pages and comment on the link here.**
Also, Dice Game is a very broad term to describe a game, can you explain to us what your game is about, the rules, and how to play? We would like to have some more info on the game.

**Comment by PathakTushar** [comment]
https://pathaktushar.github.io/TimePassGames/

**Comment by PathakTushar** [comment]
also i have added a rules button which contains all the rules and how to play the game.

**Comment by SiddharthaBhattacharjee** [comment]
Thank you for your contribution, Your game is really great, and I think it will be an amazing addition to our project. 
However, it is only multiplayer as of now, we are adding the game to the project now and we will add a single-player mode to the game in the future (an issue will be created for this). Also, your game is not responsive for mobile devices, so an issue will be created for making it responsive.  We will greatly appreciate it if you take up the above-mentioned issues, as you are the best person to work on your game.

**Pull request merged**
