### PR TITLE
added ping pong

### PR DESCRIPTION
**Pull request by Harshvg2021**
Made changes to the bar in pin pong game

### CODE REVIEW

**Comment by SiddharthaBhattacharjee** [comment]
Please deploy your branch and share the link.

**Comment by Harshvg2021** [comment]
https://harshvg2021.github.io/TimePassGames/

**Comment by SiddharthaBhattacharjee** [comment]
Thank You for contributing, It's a major improvement over the last version, Your game is now very enjoyable, we are adding your game to our project. 
We however need to make a few tweaks , firstly a score system is needed for the game , secondly touch screen support needs to be added. An issue about the same will be created , I would really appreciate if you worked on that issue, as you are the best person to work on your game.

**Comment by Harshvg2021** [comment]
Sure , i will learn about phone compatiblilty and try to make changes

**Comment by SiddharthaBhattacharjee** [comment]
I would suggest to start with adding score system , make the score system to this game , add an issue about it , and then create a PR addressing that issue.

**Pull request merged**
