### PR TITLE
Click-Shape-Game

### PR DESCRIPTION
**Pull request by Sivasanath06**
Hey, @SiddharthaBhattacharjee I uploaded my project. I want you to merge my folder with the label hack October fest.
I uploaded the deployed link in the readme file.
Hope you like it✌.
Thank you.

### CODE REVIEW

**Comment by Sivasanath06** [comment]
So you need the deployed link to paste here.

**Comment by SiddharthaBhattacharjee** [comment]
Yes , please deploy the branch you made the changes in , and comment the link here

**Comment by Sivasanath06** [comment]
.deploy noop

**Comment by Sivasanath06** [comment]
https://silver-moxie-057b91.netlify.app/

**Comment by SiddharthaBhattacharjee** [comment]
Not this one , I want you to host the fork you made from the project repo, so that we can check how you added the game to home page. So host the forked TimepassGames repo branch in which you made the changes.

**Comment by SiddharthaBhattacharjee** [comment]
As far as I can see in your repo , you haven't added your game to the home page yet , please do that and then host your branch , then comment that link with a new Pull Request, I am closing this Pull Request, do as instructed and create the new one.

**Pull request closed without merging**
