### PR TITLE
Add a game sudoku

### PR DESCRIPTION
**Pull request by Souvik2376**

### CODE REVIEW

**Comment by SiddharthaBhattacharjee** [comment]
The quiz.py game isn't comparable with our project , please remove it.
Secondly please host the branch and comment the link here so that we can evaluate the game and it's integration with the rest of the project.

**Comment by SiddharthaBhattacharjee** [comment]
Please make a new Pull request after removing the quiz.py game and providing the hosted page link.

**Comment by Souvik2376** [comment]
Please close the privious pr thn

**Comment by SiddharthaBhattacharjee** [comment]
It has been closed already

**Pull request closed without merging**
